[package]
name = "unzippy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
generator = "0.7.3"
image = "0.24.5"
zip = "0.6.4"
